# Generated by Django 4.0.3 on 2022-03-17 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
