# Generated by Django 4.0.3 on 2022-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tasks_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due',
            field=models.DateTimeField(null=True),
        ),
    ]
